### PR TITLE
Draft of STAC -> dc_load

### PR DESCRIPTION
**Pull request by Kirill888**
First working version,

Draft PR for visibility

### CODE REVIEW

**Comment by Kirill888** [comment]
ping @gadomski @matthewhanson

to try it on planetary computer do

```bash
git clone --branch kk https://github.com/Kirill888/odc-tools.git
cd odc-tools
./scripts/dev-install.sh
cd notebooks
pip install jupytext
jupytext --to notebook dc-load-from-stac-S2.py
```

then you should be able to open and run `dc-load-from-stac-S2.ipynb`, will need to select default kernel before running.

To install conda style one should do
```
conda install datacube==1.8.5 jupytext
```

but that didn't resolve for me.

**Comment by gadomski** [comment]
@Kirill888 awesome, stoked to see this coming together! I haven't gotten to a review yet, but just glancing at the diff, it looks like the dev is happening in `libs/index`. Is the plan still to eventually move this to a new lib, e.g. `libs/stac`? If we want this to be pip-installable as `pip install odc-tools-stac` or whatever, we'll need it in its own namespace package, correct?

**Comment by matthewhanson** [comment]
@Kirill888 this looks great!  I've managed to get the whole notebook running and am playing with it some.

Maybe this is more of an ODC question, but I'm wondering why `spatial_ref` is a Coordinate rather than just an attribute.  Also when we talk next maybe you could give us an overview of using bands be coordinates vs data variables in a DataSet, maybe this depends on use case, and coordinates are useful here for RGB visualizations?

**Comment by Kirill888** [comment]
> @Kirill888 awesome, stoked to see this coming together! I haven't gotten to a review yet, but just glancing at the diff, it looks like the dev is happening in `libs/index`. Is the plan still to eventually move this to a new lib, e.g. `libs/stac`? If we want this to be pip-installable as `pip install odc-tools-stac` or whatever, we'll need it in its own namespace package, correct?

So issue is this: we have too many packages as it is. Currently there is 1:1 correspondence between `odc.{lib}` and pypi package name, but it doesn't have to be. One could have a single package that ships 2 or more submodules, for example `odc.{index, stac}`. I placed it under `odc/index` package because that's where these kind of operations are currently. But we should certainly move things around/rename. `odc.index` package currently contains a bunch of tools that are missing from `datacube.` proper, tools to do with constructing various components of datacube without connecting to the database. These are all needed for `STAC.load` anyway, so a separate `odc-stac` would still need to depend on `odc-index`. Various STAC related tooling is also currently in that lib. What we can do in short term is to move stac related functionality into `odc.stac.*` while still keeping it in the same package that contains `odc.index.*`. We can also rename `odc-index` to `odc-stac` at the package and file system level.

**Comment by Kirill888** [comment]
> Maybe this is more of an ODC question, but I'm wondering why `spatial_ref` is a Coordinate rather than just an attribute. 

Coordinate is much more resilient when computing derived bands. If you do some band math, attributes can sometimes disappear from the result and one need to remember to propagate that manually, not a problem with dimensionless coordinate though.

>Also when we talk next maybe you could give us an overview of using bands be coordinates vs data variables in a DataSet, maybe this depends on use case, and coordinates are useful here for RGB visualizations?

We only use that for "8-bit per channel rgb" variables, as this is what's expected from plotting/saving to disk tooling, your normal `dc_load` returns bands as separate variables on `xr.Dataset` object. `to_rgba` and `colorize` take band(s) and turn them into a single data variable with an extra `rgba` dimension.

**Comment by Kirill888** [comment]
@gadomski and regarding 
> "nice to haves" wrt the planetary computer interface

### JupyterLab

Would be nice to have some more "dev" extensions installed

```yaml
dependencies:
  - nbdime    # Diff notebook
  - jupytext  # Save notebooks in git friendly format
  - sidecar   # Display things to the side (good for maps)
  - ipycanvas # Draw things

# code formatting tools 
# (used by jupyterlab-code-formatter that doesn't have conda)
  - black 
  - isort
  - autopep8
  - pip=20
  - pip:
    - jupyterlab-code-formatter  # Code formatting in a notebook
    - jupyterlab-code-snippets   # Snippet managament for common tasks

```

It would also be helpful to have more CLI tools installed, things like

```
apt-get install htop tmux fish zsh tig
```

**Comment by Kirill888** [comment]
It's here now: https://github.com/opendatacube/odc-tools/pull/335

**Pull request closed without merging**
